# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under house_prices_kaggle/resources/*
# and house_prices_kaggle/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for house-prices-kaggle Prod

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./house_prices_kaggle

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: house-prices-kaggle-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
